### ISSUE TITLE
Displaced and split shadows from certain view angles

### ISSUE THREAD

**Issue by viperphase1** [StrandedKitty/three-csm#1]
@vtHawk 
Thanks so much for this project. There is a pretty big issue though that is preventing me from using it.

At certain angles the shadows are offset by a large amount. It happens even when I set the number of cascades to 1.

![Screenshot from 2020-01-14 20-09-41](https://user-images.githubusercontent.com/18685519/72401929-b7bc6800-370a-11ea-8960-c2ea0ac06eb6.png)
![Screenshot from 2020-01-14 20-10-07](https://user-images.githubusercontent.com/18685519/72401940-bdb24900-370a-11ea-9d74-8b5e0d823e23.png)
![Screenshot from 2020-01-14 20-10-42](https://user-images.githubusercontent.com/18685519/72401946-c3a82a00-370a-11ea-8697-8b61d01411f3.png)

Interestingly when the viewport is taller the shadow moves in the other direction. Also there seems to be a line where the shadow is cut. Sometimes only part of the shadow is displaced.

![Screenshot from 2020-01-14 21-00-09](https://user-images.githubusercontent.com/18685519/72404000-1edd1b00-3711-11ea-978e-6c8645b558b0.png)

Clients will probably not find those exact angles but they will see a short blip as they rotate the model. If it weren't for that this package would be perfect. Really good job. Unfortunately I have no idea how to fix this problem. I'm hoping that you as the creator would have enough context to know why this is happening.

**Comment by viperphase1** [comment]
Interestingly when the viewport is taller the shadow moves in the other direction. Also there seems to be a line where the shadow is cut. Sometimes only part of the shadow is displaced.

![Screenshot from 2020-01-14 21-00-09](https://user-images.githubusercontent.com/18685519/72404000-1edd1b00-3711-11ea-978e-6c8645b558b0.png)

**Comment by StrandedKitty** [comment]
@viperphase1 Thank you for opening this issue.
I'm aware some glitches may appear if the mesh which receives shadows is to large. I don't really remember what causes it, but it may have something to do with the fact that shaders use single-precision floats.
So try making your PlaneGeometry smaller or increase number of its segments.

**Comment by viperphase1** [comment]
You were right! Increasing the number of segments fixed the problem.
I was using a 1000x1000 shadow plane and just had to change the width and height segments to 2.
