### ISSUE TITLE
Configurable light color

### ISSUE THREAD

**Issue by UstymUkhman** [StrandedKitty/three-csm#13]
Hey! Awesome plugin, really <3 it. I've noticed that the white color for `DirectionalLight`s is hardcoded right [here](https://github.com/vHawk/three-csm/blob/master/src/CSM.js#L58), so I'd like to suggest to make it configurable from data params we're passing to the constructor for the CSM initialization.

As a workaround I'm currently using this hack:

```
this.csm = new CSM({ ... });

this.csm.lights.forEach(light =>
  light.color.set(0xffff00)
);
```

But I don't think that's ideal, what do you think about that?

**Comment by itsdouges** [comment]
@StrandedKitty heya would you be open to a contribution for this? https://github.com/StrandedKitty/three-csm/blob/master/src/CSM.ts#L130

Would just be adding another property to the constructor `lightColor` I suppose 😄

**Comment by StrandedKitty** [comment]
`settings.lightColor` was introduced in 3.2.0.
