### ISSUE TITLE
`breaks - 1` should be `breaks.length - 1`?

### ISSUE THREAD

**Issue by jhurliman** [StrandedKitty/three-csm#15]
https://github.com/vHawk/three-csm/blob/3f1ec07ef0248c774cbeaa9134f595c6c906aa34/src/Frustum.js#L113

Should this be `breaks.length - 1`? It looks like `breaks` is meant to be an array here.

**Comment by StrandedKitty** [comment]
Thanks, this typo didn't really break anything and I guess that's why I didn't notice it. Fixed in c3e334929bdbdb77d9d9e4f102b12dd4474b18d9
