### ISSUE TITLE
Shadow artifacts on flat surfaces

### ISSUE THREAD

**Issue by kriffe** [StrandedKitty/three-csm#19]
Shadow artifacts appears on surfaces and are hard to compensate for. Appears for all frustrum split modes, but seems to be worst for lograthitmic

What is the cause? And are there any ways to compensate to remove this?

![image](https://user-images.githubusercontent.com/10418534/183876388-f8377f05-d92b-4d43-8672-e73c179aa671.png)

Test in https://threejs.org/examples/webgl_shadowmap_csm.html

**Comment by swift502** [comment]
I can't speak for the cause, but this seems to be a common inherent property of most real-time shadow implementations. In Blender's Eevee renderer the same thing happens.

![image](https://user-images.githubusercontent.com/24359130/183889911-bb8039d5-ea69-438a-8366-deba43e15ead.png)

The only remedies I know of are the traditional tweaking "near" and "far" shadow distances, and tweaking "shadowBias". I don't see shadowBias exposed in the demo but it should be a setting in the code.

**Comment by swift502** [comment]
The logarithmic mode is probably the worst because it has extreme cascade splits that probably aren't useful in many real-world cases. It makes some of the shadow maps unnecessarily huge and therefore very low res, introducing the artifacts.

Do you need to use the logarithmic mode though? The artifacts don't appear in "practical" mode right?

**Comment by StrandedKitty** [comment]
Hi, it's called shadow acne. You should try tuning `shadowBias` as @swift502 pointed out. Basically, the less detailed shadow map is the larger `shadowBias` value should be (I mean value in absolute units, it is possible that you actually need a negative value, I don't remember exactly). And faraway cascades are not detailed at all, so they need a larger `shadowBias`, but in this implementation all the cascades share the same bias value and you can't specify one per cascade.

The most straightforward way to fix bias for different cascades is to just scale it by camera size. I will look into this, it should be easy to implement.

**Comment by kriffe** [comment]
> The logarithmic mode is probably the worst because it has extreme cascade splits that probably aren't useful in many real-world cases. It makes some of the shadow maps unnecessarily huge and therefore very low res, introducing the artifacts.
> 
> Do you need to use the logarithmic mode though? The artifacts don't appear in "practical" mode right?

@swift502 Thank you for the quick reply. Practical mode is good enough. But I get the same artifacts for practical mode in another application so I used the logarithmic mode to illustrate the problem in the open example.

**Comment by kriffe** [comment]
> The most straightforward way to fix bias for different cascades is to just scale it by camera size. I will look into this, it should be easy to implement.

@vHawk Thank you for the suggestions and finally having a name for the problem. I have played around with shadowBias but it tends to give artifacts in other areas instead. Automatic scaling by camera size sounds like a clever way to handle it. Perhaps bias could be adjusted with faraway distance could have a positive impact?

**Comment by StrandedKitty** [comment]
I've added a slider to tweak `shadowBias` for you to better understand how it affects shadows. Also, actual bias value is now proportional to cascade camera size, it should help with artifacts in distant cascades.
