### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by swift502** [StrandedKitty/three-csm#2]
I think this should really be in three.js examples. Have you tried contacting @mrdoob and telling him about this?

As far as I know cascaded shadow maps haven't been available in three.js for a long time. And unless you know of some other attempts, this might be the only working implementation out there. If you think your implementation is usable (not terribly unoptimised), I think people should know definitely know that this exists.

I'll try to implement it in my project over the weekend. If it'll work, again, thanks a lot!

**Comment by StrandedKitty** [comment]
I'm glad you find my work useful.

However, my implementation of CSMs is obviously very "hacky" and inelegant, because I wanted it to be a separate three.js plug-in. Also it was tested only with three.js v109 and might not work with newer versions, so I don't think it is a great idea to present it as a finished "extension".

It would be great to make CSMs part of the main library, but for now I'm not looking forward to contributing to three.js. The CSM technique is fairly simple and straightforward, so maybe you can ask someone among three.js contributors who is familiar with its codebase to implement it.

If you will face any problems while implemeting it in your project feel free to ask for help.

**Comment by swift502** [comment]
Sure thing! I'll give it a try and see how it goes. 

The thing is, again, I'm not aware of any other three.js CSM implementation. If this was currently the only example of CSM, then it's the best example of CSM. The example could just use your package in it's current state. From what I remember lot of things in three.js examples are "hacky", or not parts of the official three.js repository. (e.g. I think the [cloth example](https://threejs.org/examples/#webgl_animation_cloth) literally adds nothing nor uses anything cloth related from three.js, it's a completely separate, self contained piece of code)

It would serve the purpose of letting people know someone even attempted to implement CSM again possibly for the first time [in 5 years](https://github.com/mrdoob/three.js/issues/5536#issuecomment-141166976) since they've been removed, not necessarily claim this is the perfect implementation.

**Comment by StrandedKitty** [comment]
Well, if you think so, maybe I will try to add my implemetation to three.js repository as an example. 

Thanks for your support.

**Comment by swift502** [comment]
No problem, I'm just glad I found this tiny hidden repository with 2 stars. 😄
You can ask around on the three.js forums, or straight up make a pull request adding a new example (your demo in it's current state) and see what the maintainers think of it. If you don't find the time, I'll be happy to ask around myself.

**Comment by mrdoob** [comment]
Indeed! Would be great if you guys can do a PR for this! 😊

**Comment by StrandedKitty** [comment]
@mrdoob Great, I'll make a pull request with improved example soon then.

**Comment by swift502** [comment]
https://youtu.be/00ADufA371s

- One limitation I hit is that this doesn't work with MeshLambertMaterial (maybe since it doesn't include the lights_fragment_begin shader chunk?)
- Another thing is that having to call the setupMaterial function can be a little inconvenient, but it's obvious why it's necessary at this point, and it's not impossible to comply with that.

I'm not sure how difficult would it be to "properly" merge this into three.js, get rid of the current limitations, and make it all easy-to-use. Making an example is probably a good first step...

One last time, @vtHawk thank you so much for this!
I think we can close this issue by the way. 🙂

**Comment by StrandedKitty** [comment]
I'm closing this one then.
