### ISSUE TITLE
Dispose doesn't remove lights

### ISSUE THREAD

**Issue by itsdouges** [StrandedKitty/three-csm#23]
Looking into the source dispose() doesn't remove the lights, only calling remove() does. Is this intended? According to https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects I would have expected dispose to take care of everything.

When integrating with R3F on clean up dispose is automatically called, but since remove is custom it isn't called.

**Comment by StrandedKitty** [comment]
Hmm, I don't really know why there is `CSM.remove()` method, it doesn't look very useful to me. Probably it would be okay to just get rid of it at some point.

Nevertheless, I updated `CSM.dispose()` to also remove lights from the parent and dispose them (the latter is required to clear shadowmapping resources).
