### ISSUE TITLE
React no shadows seen on this project, why ? 

### ISSUE THREAD

**Issue by espace3d** [StrandedKitty/three-csm#31]
Hi with help of [drcmda](https://discourse.threejs.org/u/drcmda) 

The following code produce no errors but not shadows are seen. Why ?

https://codesandbox.io/s/basic-example-react-csm-three-utfjwl?file=/src/App.js

**Comment by espace3d** [comment]
> Hi with help of [drcmda](https://discourse.threejs.org/u/drcmda)
> 
> The following code produce no errors but not shadows are seen. Why ?
> 
> https://codesandbox.io/s/basic-example-react-csm-three-utfjwl?file=/src/App.js

**Comment by espace3d** [comment]
> > Hi with help of [drcmda](https://discourse.threejs.org/u/drcmda)
> > The following code produce no errors but not shadows are seen. Why ?
> > https://codesandbox.io/s/basic-example-react-csm-three-utfjwl?file=/src/App.js

Solved on the codesandbox

**Comment by tenkkov** [comment]
Code breaks with latest deps using three@0.175 and three-csm@4.2.1
