### ISSUE TITLE
Cannot create 2 instances of CSM (issue with CSM.injectInclude)

### ISSUE THREAD

**Issue by elo58** [StrandedKitty/three-csm#34]
If we create two instances of CSM, there is an issue with the injectInclude method from CSM's ctor. 
Some code parts of the shader are added two times and so, the shader's compilation fails.

**Comment by elo58** [comment]
I have created a pull request to fix this behaviour.

**Comment by StrandedKitty** [comment]
I've merged your PR, thanks.
